name: Test dispatch action
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'A version'
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: install and cache npm dependencies
      run: npm ci

